In [11]:
import pandas as pd 

def import_data(path):
    """
    importing the data into pandas dataframe

    """
    
    data = pd.read_csv(path)
    return data

df = import_data(r"C:\Users\user\Desktop\Crop Yield App\corn_data.csv")


def config_columns(data):
    """
    Configuring the columns such as stripping the excess spaces, and converting the columns to lower case
    """
    data.columns = data.columns.str.strip()
    data.columns = data.columns.str.lower()
    head = data.head(3)
    data = data.copy()
    return data


def inspect_data(data):
    """
    Inspecting the shape, structure, missing values and duplicated rows in the dataframe
    """
    print(f"The shape of the dataset")
    shape = data.shape
    print(shape)

    print()

    print(f"The structure and datatype of the dataset")
    structure = data.info()
    print(structure)

    print()

    print(f"The missing values in the dataset")
    missing_values = data.isna().sum()
    print(missing_values)

    print()

    print(f"The duplicated rows in the dataset:", data.duplicated().sum())
    
    



def clean_data(data):
    """
    Cleaning the data such as imputing 'unknown into all missing categorical columns and imputing the mean intothe missing numeric variables '
    """
    data = data.copy()
    for column in data:
        if data[column].dtypes == "object":
            data[column].fillna('unknown', inplace=True)
        elif data[column].dtypes != 'O':
            data[column].fillna(data[column].mean(), inplace=True)
        else:
            print(f"No Null value in the dataset")
    return data
 

def get_counts(data):
    """
    Exploring the data by checking the value counts of each variable
    """
    data = data.copy()
    for i in data:
        counts = data[i].value_counts()
        print(counts)




def split_data(data):
    """
    Splitting the data into independent variables and dependent variable
    """
    x = data.drop(['Yield'], axis=1)
    y = data['Yield']
    return x, y 



def train_set(a,b):
    """
    Training the data for modeling
    """
    from sklearn.model_selection import train_test_split
    x_train,x_test, y_train, y_test = train_test_split(a, b, test_size =0.25, random_state= 42)
    return x_train, x_test, y_train, y_test




def pipe(x):
    """
    Building a pipe that processes the data by scaling and transfroming the columns
    """
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler, OrdinalEncoder
    from sklearn.compose import ColumnTransformer

    num_pipe = Pipeline([
        ('scaler', StandardScaler())
    ])

    cat_pipe = Pipeline([
        ('scaler', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))
    ])

    transformer = ColumnTransformer(
        transformers=[
            ('pipe1', num_pipe, x.select_dtypes(include=['int','float']).columns),
            ('pipe2', cat_pipe, x.select_dtypes(include=['O']).columns)
        ],
        remainder='drop',
        n_jobs=-1
    )
    return transformer




def models():
    """
    Building the model for prediction and evaluation of the model 
    """
    from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
    from xgboost import XGBRegressor
    from sklearn.linear_model import LinearRegression
    from sklearn.tree import DecisionTreeRegressor
    models = {
        'RF': RandomForestRegressor(),
        'XGB': XGBRegressor(),
        'LR': LinearRegression(),
        'GR': GradientBoostingRegressor(),
        'TREE': DecisionTreeRegressor()
    }
    
    from sklearn.pipeline import make_pipeline
    from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, r2_score
    for name, model in models.items():
        y_predict = make_pipeline(processor, model).fit(x_train, y_train).predict(x_test)
        print(f"The R2_Score of the {name} model is {r2_score(y_test, y_predict):.2f}")
        print(f"The MAE of the {name} model is: {mean_absolute_error(y_test, y_predict):.2f}")
        print(f"The MAPE of the {name} model is: {mean_absolute_percentage_error(y_test, y_predict):.2f}")

df = (config_columns(df))
inspect_data(df)
get_counts(clean_df)
x, y = split_data(clean_df)
x_train, x_test, y_train, y_test = train_set(x,y)
processor = pipe(x)
models()

The shape of the dataset
(422, 22)

The structure and datatype of the dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   county                422 non-null    object
 1   farmer                422 non-null    object
 2   education             396 non-null    object
 3   gender                422 non-null    object
 4   age bracket           422 non-null    object
 5   household size        422 non-null    int64
 6   crop                  422 non-null    object
 7   acreage               351 non-null    float64
 8   fertilizer amount     422 non-null    int64
 9   laborers              422 non-null    int64
 10  yield                 422 non-null    int64
 11  power source          422 non-null    object
 12  water source          422 non-null    object
 13  main credit source    422 non-null    object
 14  crop insurance        422 non-null    object
 15  farm records          422 non-null    object
 16  main advisory source  422 non-null    object
 17  extension provider    422 non-null    object
 18  advisory format       422 non-null    object
 19  advisory language     422 non-null    object
 20  latitude              422 non-null    float64
 21  longitude             422 non-null    float64
dtypes: float64(3), int64(4), object(15)
memory usage: 72.7+ KB
None

The missing values in the dataset
county                   0
farmer                   0
education               26
gender                   0
age bracket              0
household size           0
crop                     0
acreage                 71
fertilizer amount        0
laborers                 0
yield                    0
power source             0
water source             0
main credit source       0
crop insurance           0
farm records             0
main advisory source     0
extension provider       0
advisory format          0
advisory language        0
latitude                 0
longitude                0
dtype: int64

The duplicated rows in the dataset: 0
County
TAITA TAVETA    422
Name: count, dtype: int64
Farmer
fmr_65     1
fmr_219    1
fmr_72     1
fmr_71     1
fmr_368    1
          ..
fmr_410    1
fmr_371    1
fmr_274    1
fmr_254    1
fmr_200    1
Name: count, Length: 422, dtype: int64
Education
Primary        238
Secondary      126
unknown         26
Certificate     15
Diploma         11
Degree           6
Name: count, dtype: int64
Gender
Female    299
Male      123
Name: count, dtype: int64
Age bracket
36-45       132
46-55       110
18-35        90
56-65        70
above 65     20
Name: count, dtype: int64
Household size
5    94
3    83
4    75
6    73
2    46
1    21
7    16
8     9
9     5
Name: count, dtype: int64
Crop
corn    422
Name: count, dtype: int64
Acreage
0.500000    107
1.000000     97
0.828063     71
0.250000     64
1.500000     25
2.000000     22
0.750000     19
0.300000      8
3.000000      4
2.500000      4
4.000000      1
Name: count, dtype: int64
Fertilizer amount
50     108
20      71
25      54
100     45
30      29
40      28
150     20
200     10
70       7
90       6
250      5
300      4
120      4
75       4
60       3
80       3
35       2
350      2
31       2
45       2
22       1
480      1
42       1
400      1
21       1
220      1
24       1
37       1
23       1
500      1
251      1
48       1
180      1
Name: count, dtype: int64
Laborers
2    187
3    153
4     52
5     23
6      6
8      1
Name: count, dtype: int64
Yield
180    68
270    51
360    49
90     38
100    30
450    27
50     23
150    21
200    18
330    15
540    14
250     9
80      6
300     6
160     6
135     6
400     4
70      4
110     3
60      3
550     3
500     3
220     2
600     2
75      2
440     1
240     1
126     1
115     1
560     1
95      1
78      1
125     1
120     1
Name: count, dtype: int64
Power source
Manual    422
Name: count, dtype: int64
Water source
Rain    422
Name: count, dtype: int64
Main credit source
Credit groups    321
Family            73
Savings           28
Name: count, dtype: int64
Crop insurance
No    422
Name: count, dtype: int64
Farm records
No     303
Yes    119
Name: count, dtype: int64
Main advisory source
Radio                 188
Public gatherings     105
Extension services    102
Television             14
Internet               13
Name: count, dtype: int64
Extension provider
County Government      245
Private Provider       122
National Government     40
KALRO                   15
Name: count, dtype: int64
Advisory format
Phone Calls    286
SMS text       136
Name: count, dtype: int64
Advisory language
Kiswahili     321
English        55
Vernacular     46
Name: count, dtype: int64
Latitude
-3.34    39
-3.39    33
-3.50    33
-3.41    28
-3.38    25
-3.51    23
-3.36    23
-3.47    20
-3.37    20
-3.49    18
-3.42    17
-3.55    14
-3.48    12
-3.40    11
-3.35    11
-3.30     9
-3.46     9
-3.45     8
-3.27     7
-3.33     7
-3.32     7
-3.31     7
-3.56     5
-3.52     5
-3.29     5
-3.44     4
-3.25     3
-3.53     3
-3.64     3
-3.43     3
-3.26     2
-3.63     2
-3.54     2
-3.58     2
-3.28     1
-3.62     1
Name: count, dtype: int64
Longitude
38.58    50
38.37    50
38.33    41
38.36    39
38.35    32
38.38    31
38.39    29
38.40    28
38.34    27
38.59    18
38.41    13
38.30    12
38.31    11
38.32     8
38.29     7
38.42     6
38.60     6
38.61     5
38.43     2
38.56     2
38.63     1
38.27     1
38.28     1
38.57     1
38.49     1
Name: count, dtype: int64
The R2_Score of the RF model is 0.86
The MAE of the RF model is: 40.29
The MAPE of the RF model is: 0.21
The R2_Score of the XGB model is 0.86
The MAE of the XGB model is: 38.88
The MAPE of the XGB model is: 0.21
The R2_Score of the LR model is 0.83
The MAE of the LR model is: 43.26
The MAPE of the LR model is: 0.25
The R2_Score of the GR model is 0.75
The MAE of the GR model is: 56.73
The MAPE of the GR model is: 0.36
The R2_Score of the TREE model is 0.76
The MAE of the TREE model is: 50.53
The MAPE of the TREE model is: 0.27